[package]
name = "rs-reserv-service"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.52.3", features = ["full", "rt-multi-thread", "macros"] }
axum = "0.8"
serde = { version = "1.0.229", features = ["derive"] }
sqlx = { version = "0.9", features = [
    "runtime-tokio",
    "tls-native-tls",
    "postgres",
    "migrate",
    "sqlx-toml",
    "json",
    "chrono",
    "bigdecimal",
] }
bigdecimal = { version = "0.4.10", features = ["serde"]}
